apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://payment-service-prometheus:9090
    isDefault: true
  - name: Tempo
    type: tempo
    access: proxy
    url: http://payment-service-tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prom'
      tracesToMetrics:
        datasourceUid: 'prom'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
  - name: Loki
    type: loki
    access: proxy
    url: http://payment-service-loki:3100
    jsonData:
      maxLines: 1000

