global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service-app:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['payment-service-postgres-exporter:9187']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['payment-service-otel-collector:8889']
